"""Point d'entrée du package des modèles SQLAlchemy : réexporte les tables et énumérations
de chaque module pour que le reste de l'API fasse `from pbm_api.models import X`."""

from pbm_api.models.ai_usage import AiUsageMonthly
from pbm_api.models.base import Base
from pbm_api.models.catalog import (
    Card,
    CardInsight,
    CardInsightReport,
    CardName,
    CardPriceDaily,
    CardTournamentPresence,
    PriceSource,
    PriceVariant,
    Set,
    TournamentPresenceStatus,
)
from pbm_api.models.collection import (
    CollectionItem,
    Detection,
    DetectionStatus,
    Upload,
    UploadStatus,
)
from pbm_api.models.decks import (
    DECK_EVENT_CARD_INCOMPLETE,
    DECK_EVENT_REASON_COUNTERFEIT,
    DECK_EVENT_REASON_REMOVED,
    Deck,
    DeckCard,
    DeckEvent,
)
from pbm_api.models.game_launch import (
    LANCEMENT_STATUT_ABANDONNE,
    LANCEMENT_STATUT_LANCE,
    LANCEMENT_STATUT_PREPARATION,
    LANCEMENT_STATUT_TIRAGE,
    LANCEMENT_STATUTS,
    GameLaunch,
)
from pbm_api.models.games import (
    GAME_STATUS_EN_COURS,
    GAME_STATUS_EXPIREE,
    GAME_STATUS_TERMINEE,
    GAME_STATUTS,
    Game,
    GameEvent,
    GamePlayer,
    GameSnapshot,
)
from pbm_api.models.identification import (
    CardVisualIndex,
    IdentificationCache,
    IdentificationCorrection,
)
from pbm_api.models.invitations import (
    INVITATION_MODE_LIEN,
    INVITATION_MODE_PSEUDO,
    INVITATION_MODES,
    INVITATION_STATUT_ACCEPTEE,
    INVITATION_STATUT_ANNULEE,
    INVITATION_STATUT_ENVOYEE,
    INVITATION_STATUT_EXPIREE,
    INVITATION_STATUT_REFUSEE,
    INVITATION_STATUTS,
    GameInvitation,
)
from pbm_api.models.jobs import DataExport, Job, JobStatus
from pbm_api.models.pricing import ExchangeRateDaily
from pbm_api.models.users import AiCredential, AiProvider, EmailToken, EmailTokenKind, Session, User
from pbm_api.models.wishlist import WishlistItem

__all__ = [
    "Base",
    "User",
    "Session",
    "EmailToken",
    "EmailTokenKind",
    "AiCredential",
    "AiProvider",
    "AiUsageMonthly",
    "Set",
    "Card",
    "CardName",
    "CardPriceDaily",
    "PriceSource",
    "PriceVariant",
    "CardInsight",
    "CardInsightReport",
    "CardTournamentPresence",
    "TournamentPresenceStatus",
    "Upload",
    "UploadStatus",
    "Detection",
    "DetectionStatus",
    "Deck",
    "DeckCard",
    "DeckEvent",
    "DECK_EVENT_CARD_INCOMPLETE",
    "DECK_EVENT_REASON_REMOVED",
    "DECK_EVENT_REASON_COUNTERFEIT",
    "Game",
    "GamePlayer",
    "GameEvent",
    "GameSnapshot",
    "GAME_STATUS_EN_COURS",
    "GAME_STATUS_TERMINEE",
    "GAME_STATUS_EXPIREE",
    "GAME_STATUTS",
    "GameInvitation",
    "INVITATION_MODE_PSEUDO",
    "INVITATION_MODE_LIEN",
    "INVITATION_MODES",
    "INVITATION_STATUT_ENVOYEE",
    "INVITATION_STATUT_ACCEPTEE",
    "INVITATION_STATUT_REFUSEE",
    "INVITATION_STATUT_ANNULEE",
    "INVITATION_STATUT_EXPIREE",
    "INVITATION_STATUTS",
    "CollectionItem",
    "IdentificationCache",
    "IdentificationCorrection",
    "CardVisualIndex",
    "Job",
    "JobStatus",
    "DataExport",
    "ExchangeRateDaily",
    "WishlistItem",
    "GameLaunch",
    "LANCEMENT_STATUT_PREPARATION",
    "LANCEMENT_STATUT_TIRAGE",
    "LANCEMENT_STATUT_LANCE",
    "LANCEMENT_STATUT_ABANDONNE",
    "LANCEMENT_STATUTS",
]
