"""identification cache and detection extraction

Revision ID: 054d503ae627
Revises: 7fc6cd5efc72
Create Date: 2026-09-19 22:41:52.722441

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '054d503ae627'
down_revision: str | Sequence[str] | None = '2e56ba32d5ed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identification_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phash', sa.BigInteger(), nullable=False),
    sa.Column('extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_identification_cache_phash', 'identification_cache', ['phash'], unique=False)
    op.add_column('detections', sa.Column('extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # `card_insight_reports.created_at` : autogenerate signale aussi un changement de type
    # (TIMESTAMP(timezone=True) -> DateTime()) sans rapport avec ce lot — un artefact du
    # comparateur d'Alembic sur une colonne posée par le lot `v4-anecdotes`, pas un drift réel
    # (même type Postgres). Volontairement omis : hors périmètre de ce lot.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detections', 'extraction')
    op.drop_index('ix_identification_cache_phash', table_name='identification_cache')
    op.drop_table('identification_cache')
    # ### end Alembic commands ###
