"""detection condition assessment and collection item counterfeit flag

Revision ID: 066f6a4397cb
Revises: 328aef94ea58
Create Date: 2026-09-19 23:20:19.134261

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '066f6a4397cb'
down_revision: str | Sequence[str] | None = '328aef94ea58'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # `card_insight_reports.created_at` (TIMESTAMP(timezone=True) -> DateTime()) omis
    # volontairement : artefact déjà documenté du comparateur d'Alembic sur une colonne posée
    # par `v4-anecdotes` (même type Postgres, voir la migration `054d503ae627`), sans rapport
    # avec ce lot.
    op.add_column(
        'collection_items',
        sa.Column('counterfeit_suspected', sa.Boolean(), server_default='false', nullable=False),
    )
    op.add_column('detections', sa.Column('condition_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detections', 'condition_assessment')
    op.drop_column('collection_items', 'counterfeit_suspected')
    # ### end Alembic commands ###
