"""catalog reconciliation and image fields

Revision ID: 1d51087de4ae
Revises: 5e0d551b788e
Create Date: 2026-09-19 20:38:31.111493

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d51087de4ae'
down_revision: str | Sequence[str] | None = '5e0d551b788e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('illustrator', sa.String(length=255), nullable=True))
    op.add_column('cards', sa.Column('attacks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cards', sa.Column('abilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cards', sa.Column('legal_standard', sa.Boolean(), nullable=True))
    op.add_column('cards', sa.Column('legal_expanded', sa.Boolean(), nullable=True))
    op.add_column('cards', sa.Column('tcgdex_id', sa.String(length=64), nullable=True))
    op.add_column('cards', sa.Column('ptcg_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_cards_ptcg_id'), 'cards', ['ptcg_id'], unique=False)
    op.create_unique_constraint('uq_cards_tcgdex_id', 'cards', ['tcgdex_id'])
    op.add_column('sets', sa.Column('tcgdex_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_sets_tcgdex_id', 'sets', ['tcgdex_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sets_tcgdex_id', 'sets', type_='unique')
    op.drop_column('sets', 'tcgdex_id')
    op.drop_constraint('uq_cards_tcgdex_id', 'cards', type_='unique')
    op.drop_index(op.f('ix_cards_ptcg_id'), table_name='cards')
    op.drop_column('cards', 'ptcg_id')
    op.drop_column('cards', 'tcgdex_id')
    op.drop_column('cards', 'legal_expanded')
    op.drop_column('cards', 'legal_standard')
    op.drop_column('cards', 'abilities')
    op.drop_column('cards', 'attacks')
    op.drop_column('cards', 'illustrator')
    # ### end Alembic commands ###
