"""tournament presence and in-game study cache

Revision ID: 5e8f243e399f
Revises: 7fc6cd5efc72
Create Date: 2026-09-19 22:43:40.028681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e8f243e399f'
down_revision: Union[str, Sequence[str], None] = '328aef94ea58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_tournament_presence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('checked', 'unavailable', name='tournament_presence_status'), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('decks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id')
    )
    op.add_column('card_insights', sa.Column('game_study_source_model', sa.String(length=64), nullable=True))
    op.add_column('card_insights', sa.Column('game_study_generated_at', sa.DateTime(), nullable=True))
    op.add_column('card_insights', sa.Column('game_study_cached_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_insights', 'game_study_cached_until')
    op.drop_column('card_insights', 'game_study_generated_at')
    op.drop_column('card_insights', 'game_study_source_model')
    op.drop_table('card_tournament_presence')
    # ### end Alembic commands ###
    sa.Enum(name='tournament_presence_status').drop(op.get_bind(), checkfirst=True)
