"""exchange rates daily and user preferred currency

Revision ID: 8565c4640de8
Revises: 1d51087de4ae
Create Date: 2026-09-19 21:09:19.967889

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8565c4640de8'
down_revision: str | Sequence[str] | None = '1d51087de4ae'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'currency', name='uq_exchange_rates_daily_day_currency')
    )
    op.create_index(op.f('ix_exchange_rates_daily_day'), 'exchange_rates_daily', ['day'], unique=False)
    op.add_column('users', sa.Column('preferred_currency', sa.String(length=3), server_default='EUR', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_currency')
    op.drop_index(op.f('ix_exchange_rates_daily_day'), table_name='exchange_rates_daily')
    op.drop_table('exchange_rates_daily')
    # ### end Alembic commands ###
