"""card_completeness_fields

Revision ID: b671eb503fa3
Revises: d42b0620077e
Create Date: 2026-09-19 21:41:42.766476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b671eb503fa3'
down_revision: Union[str, Sequence[str], None] = 'd42b0620077e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cards', sa.Column('resistances', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cards', sa.Column('retreat_cost', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('rule_suffix', sa.String(length=32), nullable=True))
    op.add_column('cards', sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'variants')
    op.drop_column('cards', 'rule_suffix')
    op.drop_column('cards', 'retreat_cost')
    op.drop_column('cards', 'resistances')
    op.drop_column('cards', 'weaknesses')
    # ### end Alembic commands ###
