"""identification corrections journal

Revision ID: d27e4efd0255
Revises: 054d503ae627
Create Date: 2026-09-19 23:07:53.488830

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd27e4efd0255'
down_revision: str | Sequence[str] | None = '216ae1bf9f95'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identification_corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('detection_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('proposed_card_id', sa.UUID(), nullable=True),
    sa.Column('chosen_card_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chosen_card_id'], ['cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_card_id'], ['cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identification_corrections_detection_id'), 'identification_corrections', ['detection_id'], unique=False)
    op.create_index(op.f('ix_identification_corrections_user_id'), 'identification_corrections', ['user_id'], unique=False)
    # `card_insight_reports.created_at` (TIMESTAMP(timezone=True) -> DateTime()) omis comme dans
    # `054d503ae627` : artefact du comparateur d'Alembic sur une colonne posée par `v4-anecdotes`,
    # même type Postgres, sans rapport avec ce lot.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identification_corrections_user_id'), table_name='identification_corrections')
    op.drop_index(op.f('ix_identification_corrections_detection_id'), table_name='identification_corrections')
    op.drop_table('identification_corrections')
    # ### end Alembic commands ###
