"""visual index and identification method

Revision ID: f950b86db322
Revises: d27e4efd0255
Create Date: 2026-09-20 00:11:51.593035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f950b86db322'
down_revision: Union[str, Sequence[str], None] = 'd27e4efd0255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_visual_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('full_phash', sa.BigInteger(), nullable=False),
    sa.Column('illustration_phash', sa.BigInteger(), nullable=False),
    sa.Column('source_image_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'language', name='uq_card_visual_index_card_language')
    )
    op.create_index(op.f('ix_card_visual_index_card_id'), 'card_visual_index', ['card_id'], unique=False)
    op.create_index('ix_card_visual_index_full_phash', 'card_visual_index', ['full_phash'], unique=False)
    op.create_index('ix_card_visual_index_illustration_phash', 'card_visual_index', ['illustration_phash'], unique=False)
    # `card_insight_reports.created_at` (TIMESTAMP(timezone=True) -> DateTime()) omis comme dans
    # `054d503ae627`/`d27e4efd0255` : artefact récurrent du comparateur d'Alembic sur une colonne
    # posée par `v4-anecdotes`, même type Postgres réel, sans rapport avec ce lot.
    op.add_column('detections', sa.Column('identification_method', sa.String(length=16), nullable=True))
    op.add_column('identification_cache', sa.Column('method', sa.String(length=16), server_default='ia', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identification_cache', 'method')
    op.drop_column('detections', 'identification_method')
    op.drop_index('ix_card_visual_index_illustration_phash', table_name='card_visual_index')
    op.drop_index('ix_card_visual_index_full_phash', table_name='card_visual_index')
    op.drop_index(op.f('ix_card_visual_index_card_id'), table_name='card_visual_index')
    op.drop_table('card_visual_index')
    # ### end Alembic commands ###
