/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_auth_forgot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_auth_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/img/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Card Image */
        get: operations["get_card_image_img_cards__card_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/ai-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ai Keys */
        get: operations["list_ai_keys_me_ai_keys_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/ai-keys/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert Ai Key */
        put: operations["upsert_ai_key_me_ai_keys__provider__put"];
        post?: never;
        /** Delete Ai Key */
        delete: operations["delete_ai_key_me_ai_keys__provider__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/ai-keys/{provider}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Ai Key */
        post: operations["test_ai_key_me_ai_keys__provider__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/ai-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ai Settings */
        get: operations["get_ai_settings_me_ai_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Ai Settings */
        patch: operations["update_ai_settings_me_ai_settings_patch"];
        trace?: never;
    };
    "/me/ai-usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ai Usage */
        get: operations["get_ai_usage_me_ai_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Catalog */
        get: operations["search_catalog_catalog_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_me_get"];
        put?: never;
        post?: never;
        /** Delete Account */
        delete: operations["delete_account_me_delete"];
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_me_patch"];
        trace?: never;
    };
    "/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Avatar */
        get: operations["get_avatar_me_avatar_get"];
        put?: never;
        /** Upload Avatar */
        post: operations["upload_avatar_me_avatar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Email */
        post: operations["change_email_me_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/email/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Email Change */
        post: operations["confirm_email_change_me_email_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_me_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_me_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Session */
        delete: operations["revoke_session_me_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Uploads */
        post: operations["create_uploads_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{upload_id}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Raw Upload
         * @description Cible d'envoi du backend `local` (D7) : jeton signé à durée limitée, pas de session —
         *     même contrat d'usage qu'une URL présignée S3, que cette route remplace dans ce backend.
         */
        put: operations["put_raw_upload_uploads__upload_id__raw_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{upload_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Upload */
        post: operations["complete_upload_uploads__upload_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{upload_id}/detections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Detections
         * @description Cartes détectées sur un envoi (mission `v3-detection`), avec leur extraction, leurs
         *     candidats catalogue une fois identifiées (mission `v3-identification`) et leur état estimé
         *     (mission `v3-etat`) : préalable à la validation humaine (lot `v3-validation`).
         */
        get: operations["list_detections_uploads__upload_id__detections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Upload
         * @description État + détections d'un envoi (mission `v3-validation` point 1) : chargement initial de
         *     l'écran de validation, avant de bascule sur le flux SSE pour la suite de la progression.
         */
        get: operations["get_upload_uploads__upload_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{upload_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Upload Events */
        get: operations["stream_upload_events_uploads__upload_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{upload_id}/confirm-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm All Detections
         * @description « Tout ajouter » (mission point 2) : ajoute à la collection les détections dont le
         *     premier candidat est présélectionné, laisse `pending` (dans `skipped`) tout le reste.
         */
        post: operations["confirm_all_detections_uploads__upload_id__confirm_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{upload_id}/detections/{detection_id}/crop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Detection Crop */
        get: operations["get_detection_crop_uploads__upload_id__detections__detection_id__crop_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/detections/{detection_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Detection */
        post: operations["confirm_detection_detections__detection_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/detections/{detection_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Detection */
        post: operations["reject_detection_detections__detection_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/collection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Collection */
        get: operations["list_collection_me_collection_get"];
        put?: never;
        /** Create Collection Item */
        post: operations["create_collection_item_me_collection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/collection/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Collection Facets */
        get: operations["get_collection_facets_me_collection_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/collection/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Collection Item */
        get: operations["get_collection_item_me_collection__item_id__get"];
        put?: never;
        post?: never;
        /** Delete Collection Item */
        delete: operations["delete_collection_item_me_collection__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Collection Item */
        patch: operations["update_collection_item_me_collection__item_id__patch"];
        trace?: never;
    };
    "/me/collection/{item_id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Collection Item Photo
         * @description Bascule « Ma photo » de la fiche carte (mission `v4-fiche`) — jamais la photo d'un
         *     exemplaire d'un autre utilisateur (`service.get_owned_item`, même filtre que le reste de ce
         *     routeur).
         */
        get: operations["get_collection_item_photo_me_collection__item_id__photo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{card_id}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Card Insights */
        get: operations["get_card_insights_cards__card_id__insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{card_id}/insights/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report Card Insights */
        post: operations["report_card_insights_cards__card_id__insights_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Export */
        post: operations["request_export_me_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/export/{export_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Export */
        get: operations["get_export_me_export__export_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Export */
        get: operations["download_export_export_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{card_id}/in-game-study": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get In Game Study */
        get: operations["get_in_game_study_cards__card_id__in_game_study_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Card */
        get: operations["get_card_cards__card_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{card_id}/price-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Card Price History */
        get: operations["get_card_price_history_cards__card_id__price_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{card_id}/my-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Card My Items */
        get: operations["get_card_my_items_cards__card_id__my_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AiKeyResponse */
        AiKeyResponse: {
            provider: components["schemas"]["AiProvider"];
            /** Key Mask */
            key_mask: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AiKeyTestRequest */
        AiKeyTestRequest: {
            /** Api Key */
            api_key?: string | null;
        };
        /** AiKeyTestResponse */
        AiKeyTestResponse: {
            /** Valid */
            valid: boolean;
            /** Message */
            message: string;
        };
        /** AiKeyUpsertRequest */
        AiKeyUpsertRequest: {
            /** Api Key */
            api_key: string;
        };
        /**
         * AiProvider
         * @enum {string}
         */
        AiProvider: "anthropic" | "gemini" | "openai";
        /** AiSettingsResponse */
        AiSettingsResponse: {
            default_provider: components["schemas"]["AiProvider"] | null;
            /** Default Model */
            default_model: string | null;
        };
        /** AiSettingsUpdateRequest */
        AiSettingsUpdateRequest: {
            default_provider?: components["schemas"]["AiProvider"] | null;
            /** Default Model */
            default_model?: string | null;
        };
        /** AiUsageEntry */
        AiUsageEntry: {
            provider: components["schemas"]["AiProvider"];
            /**
             * Period
             * Format: date
             */
            period: string;
            /** Calls Count */
            calls_count: number;
            /** Tokens Count */
            tokens_count: number;
            /** Estimated Cost Eur */
            estimated_cost_eur: string;
        };
        /** AnecdoteOut */
        AnecdoteOut: {
            /** Text */
            text: string;
            /** Source Url */
            source_url: string;
        };
        /** Body_upload_avatar_me_avatar_post */
        Body_upload_avatar_me_avatar_post: {
            /** File */
            file: string;
        };
        /** CardDetailResponse */
        CardDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Number */
            number: string;
            /** Rarity */
            rarity: string | null;
            /** Supertype */
            supertype: string | null;
            /** Hp */
            hp: number | null;
            /** Has Image */
            has_image: boolean;
            /** Illustrator */
            illustrator: string | null;
            set: components["schemas"]["CardSetOut"];
            /** Prices Eur */
            prices_eur: {
                [key: string]: string | null;
            };
            ranking: components["schemas"]["CardRankingOut"];
            /** Owned Count */
            owned_count: number;
            collection_rank: components["schemas"]["OwnedCollectionRankOut"] | null;
        };
        /** CardInsightsResponse */
        CardInsightsResponse: {
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            /** Status */
            status: string;
            /** Anecdotes */
            anecdotes: components["schemas"]["AnecdoteOut"][];
            /** Generated At */
            generated_at: string | null;
        };
        /** CardRankingOut */
        CardRankingOut: {
            /** Rarity Rank */
            rarity_rank: number | null;
            /** Rarity Group Size */
            rarity_group_size: number | null;
            /** Value Percentile */
            value_percentile: number | null;
        };
        /** CardSearchResult */
        CardSearchResult: {
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            /**
             * Set Id
             * Format: uuid
             */
            set_id: string;
            /** Number */
            number: string;
            /** Name */
            name: string;
            /** Matched Name */
            matched_name: string;
            /** Language */
            language: string | null;
            /** Set Name */
            set_name: string;
            /** Set Code */
            set_code: string;
            /** Score */
            score: number;
        };
        /** CardSetOut */
        CardSetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Code */
            code: string;
            /** Series */
            series: string | null;
            /** Release Date */
            release_date: string | null;
            /** Total Cards */
            total_cards: number | null;
            /** Logo Url */
            logo_url: string | null;
        };
        /** ChangeEmailRequest */
        ChangeEmailRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** CollectionAggregates */
        CollectionAggregates: {
            /** Items Total */
            items_total: number;
            /** Items Priced */
            items_priced: number;
            /** Items Missing Price */
            items_missing_price: number;
            /** Total Value Eur */
            total_value_eur: string;
            /** Value Change 7D Eur */
            value_change_7d_eur: string;
            /** Value Change 30D Eur */
            value_change_30d_eur: string;
        };
        /** CollectionFacetSet */
        CollectionFacetSet: {
            /**
             * Set Id
             * Format: uuid
             */
            set_id: string;
            /** Name */
            name: string;
            /** Code */
            code: string;
        };
        /** CollectionFacets */
        CollectionFacets: {
            /** Sets */
            sets: components["schemas"]["CollectionFacetSet"][];
            /** Series */
            series: string[];
            /** Rarities */
            rarities: string[];
            /** Card Types */
            card_types: string[];
            /** Languages */
            languages: string[];
            /** Variants */
            variants: components["schemas"]["PriceVariant"][];
            /** Condition Grades */
            condition_grades: string[];
        };
        /** CollectionItemDetail */
        CollectionItemDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            /**
             * Set Id
             * Format: uuid
             */
            set_id: string;
            /** Language */
            language: string;
            variant: components["schemas"]["PriceVariant"];
            /** Condition Grade */
            condition_grade: string | null;
            /** Purchase Price */
            purchase_price: string | null;
            /** Purchase Currency */
            purchase_currency: string | null;
            /** Acquired At */
            acquired_at: string | null;
            /** Value Eur */
            value_eur: string | null;
            ranking: components["schemas"]["CollectionItemRanking"];
        };
        /** CollectionItemRanking */
        CollectionItemRanking: {
            /** Rarity Rank */
            rarity_rank: number | null;
            /** Rarity Group Size */
            rarity_group_size: number | null;
            /** Value Percentile */
            value_percentile: number | null;
            /** Collection Rank */
            collection_rank: number | null;
            /** Collection Rank Total */
            collection_rank_total: number;
        };
        /** CollectionListItem */
        CollectionListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            /**
             * Set Id
             * Format: uuid
             */
            set_id: string;
            /** Card Name */
            card_name: string;
            /** Card Number */
            card_number: string;
            /** Set Name */
            set_name: string;
            /** Set Code */
            set_code: string;
            /** Series */
            series: string | null;
            /** Rarity */
            rarity: string | null;
            /** Card Type */
            card_type: string | null;
            /** Language */
            language: string;
            variant: components["schemas"]["PriceVariant"];
            /** Condition Grade */
            condition_grade: string | null;
            /** Counterfeit Suspected */
            counterfeit_suspected: boolean;
            /** Purchase Price */
            purchase_price: string | null;
            /** Purchase Currency */
            purchase_currency: string | null;
            /** Acquired At */
            acquired_at: string | null;
            /** Value Eur */
            value_eur: string | null;
            /** Value Change 30D Eur */
            value_change_30d_eur: string | null;
            /** Value Change 30D Pct */
            value_change_30d_pct: string | null;
            /** Is Duplicate */
            is_duplicate: boolean;
        };
        /** CollectionListResponse */
        CollectionListResponse: {
            /** Items */
            items: components["schemas"]["CollectionListItem"][];
            /** Next Cursor */
            next_cursor: string | null;
            aggregates: components["schemas"]["CollectionAggregates"];
        };
        /**
         * CollectionSort
         * @enum {string}
         */
        CollectionSort: "value_desc" | "value_asc" | "value_change_30d_desc" | "value_change_30d_asc" | "acquired_at_desc" | "acquired_at_asc" | "number_asc" | "name_asc";
        /** CompleteUploadResponse */
        CompleteUploadResponse: {
            /**
             * Upload Id
             * Format: uuid
             */
            upload_id: string;
            status: components["schemas"]["UploadStatus"];
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Recognition Enabled */
            recognition_enabled: boolean;
            /** Job Id */
            job_id: string | null;
        };
        /** ConfirmAllResponse */
        ConfirmAllResponse: {
            /**
             * Upload Id
             * Format: uuid
             */
            upload_id: string;
            /** Confirmed */
            confirmed: string[];
            /** Skipped */
            skipped: string[];
        };
        /** ConfirmDetectionRequest */
        ConfirmDetectionRequest: {
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            /**
             * Language
             * @default fr
             */
            language: string;
            /** @default normal */
            variant: components["schemas"]["PriceVariant"];
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /** Condition Grade */
            condition_grade?: string | null;
            /** Purchase Price */
            purchase_price?: number | string | null;
            /** Purchase Currency */
            purchase_currency?: string | null;
            /** Acquired At */
            acquired_at?: string | null;
        };
        /** ConfirmDetectionResponse */
        ConfirmDetectionResponse: {
            /**
             * Detection Id
             * Format: uuid
             */
            detection_id: string;
            status: components["schemas"]["DetectionStatus"];
            /** Collection Item Ids */
            collection_item_ids: string[];
        };
        /** ConfirmEmailChangeRequest */
        ConfirmEmailChangeRequest: {
            /** Token */
            token: string;
        };
        /** CreateCollectionItemRequest */
        CreateCollectionItemRequest: {
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            /**
             * Language
             * @default fr
             */
            language: string;
            /** @default normal */
            variant: components["schemas"]["PriceVariant"];
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /** Condition Grade */
            condition_grade?: string | null;
            /** Purchase Price */
            purchase_price?: number | string | null;
            /** Purchase Currency */
            purchase_currency?: string | null;
            /** Acquired At */
            acquired_at?: string | null;
        };
        /** CreateCollectionItemResponse */
        CreateCollectionItemResponse: {
            /** Collection Item Ids */
            collection_item_ids: string[];
        };
        /** CreateUploadsRequest */
        CreateUploadsRequest: {
            /** Files */
            files: components["schemas"]["UploadFileRequest"][];
        };
        /** CreateUploadsResponse */
        CreateUploadsResponse: {
            /** Uploads */
            uploads: components["schemas"]["UploadTarget"][];
        };
        /** DeleteAccountRequest */
        DeleteAccountRequest: {
            /** Password */
            password: string;
        };
        /** DetectionResponse */
        DetectionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reading Order */
            reading_order: number;
            status: components["schemas"]["DetectionStatus"];
            /** Crop Url */
            crop_url: string;
            /** Extraction */
            extraction: {
                [key: string]: unknown;
            } | null;
            /** Candidates */
            candidates: unknown[] | null;
            /** Condition */
            condition: {
                [key: string]: unknown;
            } | null;
            /** Identification Method */
            identification_method: string | null;
        };
        /**
         * DetectionStatus
         * @enum {string}
         */
        DetectionStatus: "pending" | "validated" | "rejected";
        /** ExportResponse */
        ExportResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["JobStatus"];
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Completed At */
            completed_at: string | null;
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** InGameStudyResponse */
        InGameStudyResponse: {
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            legalities: components["schemas"]["LegalitiesOut"];
            prize_rule: components["schemas"]["PrizeRuleOut"];
            /** Attacks */
            attacks: {
                [key: string]: unknown;
            }[] | null;
            /** Abilities */
            abilities: {
                [key: string]: unknown;
            }[] | null;
            tournament_presence: components["schemas"]["TournamentPresenceOut"];
            study: components["schemas"]["StudyOut"];
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed";
        /** LegalitiesOut */
        LegalitiesOut: {
            /** Standard */
            standard: boolean | null;
            /** Expanded */
            expanded: boolean | null;
        };
        /** ListDetectionsResponse */
        ListDetectionsResponse: {
            /**
             * Upload Id
             * Format: uuid
             */
            upload_id: string;
            /** Detections */
            detections: components["schemas"]["DetectionResponse"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /** MyCardItemOut */
        MyCardItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Language */
            language: string;
            variant: components["schemas"]["PriceVariant"];
            /** Condition Grade */
            condition_grade: string | null;
            /** Counterfeit Suspected */
            counterfeit_suspected: boolean;
            /** Purchase Price */
            purchase_price: string | null;
            /** Purchase Currency */
            purchase_currency: string | null;
            /** Purchase Price Eur */
            purchase_price_eur: string | null;
            /** Acquired At */
            acquired_at: string | null;
            /** Value Eur */
            value_eur: string | null;
            /** Has Photo */
            has_photo: boolean;
            /** Condition Detail */
            condition_detail: {
                [key: string]: unknown;
            } | null;
        };
        /** OwnedCollectionRankOut */
        OwnedCollectionRankOut: {
            /** Position */
            position: number | null;
            /** Total Priced */
            total_priced: number;
        };
        /** PriceHistoryPoint */
        PriceHistoryPoint: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Price Eur */
            price_eur: string;
        };
        /** PriceHistoryResponse */
        PriceHistoryResponse: {
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            variant: components["schemas"]["PriceVariant"];
            /** Points */
            points: components["schemas"]["PriceHistoryPoint"][];
        };
        /**
         * PriceVariant
         * @enum {string}
         */
        PriceVariant: "normal" | "holo" | "reverse_holo" | "first_edition";
        /** PrizeRuleOut */
        PrizeRuleOut: {
            /** Applies */
            applies: boolean;
            /** Prizes Taken */
            prizes_taken: number | null;
            /** Label */
            label: string;
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Email Verified */
            email_verified: boolean;
            /** Pending Email */
            pending_email: string | null;
            /** Pseudo */
            pseudo: string | null;
            /** Has Avatar */
            has_avatar: boolean;
            /** First Name */
            first_name: string | null;
            /** Last Name */
            last_name: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Accept Terms */
            accept_terms: boolean;
        };
        /** RejectDetectionResponse */
        RejectDetectionResponse: {
            /**
             * Detection Id
             * Format: uuid
             */
            detection_id: string;
            status: components["schemas"]["DetectionStatus"];
        };
        /** ReportCardInsightRequest */
        ReportCardInsightRequest: {
            /** Reason */
            reason?: string | null;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Id */
            id: string;
            /** User Agent */
            user_agent: string | null;
            /** Ip Address */
            ip_address: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current */
            current: boolean;
        };
        /** StudyOut */
        StudyOut: {
            /** Status */
            status: string;
            /** Text */
            text: string | null;
            /** Generated At */
            generated_at: string | null;
        };
        /** TournamentDeckOut */
        TournamentDeckOut: {
            /** Deck Name */
            deck_name: string;
            /** Tournament Name */
            tournament_name: string;
            /** Tournament Url */
            tournament_url: string | null;
            /** Placement */
            placement: string;
        };
        /** TournamentPresenceOut */
        TournamentPresenceOut: {
            /** Status */
            status: string;
            /** Source Url */
            source_url: string | null;
            /** Checked At */
            checked_at: string | null;
            /** Decks */
            decks: components["schemas"]["TournamentDeckOut"][];
        };
        /**
         * UpdateCollectionItemRequest
         * @description Toute mise à jour partielle : seuls les champs effectivement envoyés sont modifiés
         *     (`exclude_unset=True` côté service) — un client peut donc corriger le seul état estimé sans
         *     reposer la langue, la variante ou le prix d'achat déjà enregistrés.
         */
        UpdateCollectionItemRequest: {
            /** Language */
            language?: string | null;
            variant?: components["schemas"]["PriceVariant"] | null;
            /** Condition Grade */
            condition_grade?: string | null;
            /** Counterfeit Suspected */
            counterfeit_suspected?: boolean | null;
            /** Purchase Price */
            purchase_price?: number | string | null;
            /** Purchase Currency */
            purchase_currency?: string | null;
            /** Acquired At */
            acquired_at?: string | null;
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            /** Pseudo */
            pseudo: string;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
        };
        /**
         * UploadDetailResponse
         * @description `GET /uploads/{id}` (mission `v3-validation` point 1) : état de l'envoi et de sa
         *     reconnaissance — chargement initial de l'écran de validation, et forme des instantanés du
         *     flux SSE `GET /uploads/{id}/events`.
         */
        UploadDetailResponse: {
            /**
             * Upload Id
             * Format: uuid
             */
            upload_id: string;
            status: components["schemas"]["UploadStatus"];
            job_status: components["schemas"]["JobStatus"] | null;
            /** Job Error */
            job_error: string | null;
            /** Detections */
            detections: components["schemas"]["DetectionResponse"][];
        };
        /** UploadFileRequest */
        UploadFileRequest: {
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /**
         * UploadStatus
         * @enum {string}
         */
        UploadStatus: "pending" | "processing" | "processed" | "failed";
        /** UploadTarget */
        UploadTarget: {
            /**
             * Upload Id
             * Format: uuid
             */
            upload_id: string;
            /** Method */
            method: string;
            /** Url */
            url: string;
            /** Headers */
            headers: {
                [key: string]: string;
            };
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Email Verified */
            email_verified: boolean;
            /** Must Change Password */
            must_change_password: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyEmailRequest */
        VerifyEmailRequest: {
            /** Token */
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forgot_password_auth_forgot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_auth_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_card_image_img_cards__card_id__get: {
        parameters: {
            query?: {
                size?: string;
            };
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ai_keys_me_ai_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiKeyResponse"][];
                };
            };
        };
    };
    upsert_ai_key_me_ai_keys__provider__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["schemas"]["AiProvider"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiKeyUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiKeyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_ai_key_me_ai_keys__provider__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["schemas"]["AiProvider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_ai_key_me_ai_keys__provider__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: components["schemas"]["AiProvider"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiKeyTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiKeyTestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ai_settings_me_ai_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiSettingsResponse"];
                };
            };
        };
    };
    update_ai_settings_me_ai_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiSettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ai_usage_me_ai_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiUsageEntry"][];
                };
            };
        };
    };
    search_catalog_catalog_search_get: {
        parameters: {
            query: {
                q: string;
                set?: string | null;
                lang?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardSearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    delete_account_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_avatar_me_avatar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    upload_avatar_me_avatar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_avatar_me_avatar_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_email_me_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_email_change_me_email_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmEmailChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_me_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_me_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"][];
                };
            };
        };
    };
    revoke_session_me_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_uploads_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUploadsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_raw_upload_uploads__upload_id__raw_put: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_upload_uploads__upload_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_detections_uploads__upload_id__detections_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDetectionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_uploads__upload_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_upload_events_uploads__upload_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_all_detections_uploads__upload_id__confirm_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmAllResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_detection_crop_uploads__upload_id__detections__detection_id__crop_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
                detection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_detection_detections__detection_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                detection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmDetectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmDetectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_detection_detections__detection_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                detection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RejectDetectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_collection_me_collection_get: {
        parameters: {
            query?: {
                q?: string | null;
                set_id?: string[] | null;
                series?: string[] | null;
                rarity?: string[] | null;
                card_type?: string[] | null;
                language?: string[] | null;
                variant?: components["schemas"]["PriceVariant"][] | null;
                condition_grade?: string[] | null;
                value_min?: number | string | null;
                value_max?: number | string | null;
                acquired_from?: string | null;
                acquired_to?: string | null;
                duplicates?: boolean;
                counterfeit?: boolean;
                sort?: components["schemas"]["CollectionSort"];
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_collection_item_me_collection_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCollectionItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCollectionItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_collection_facets_me_collection_facets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionFacets"];
                };
            };
        };
    };
    get_collection_item_me_collection__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_collection_item_me_collection__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_collection_item_me_collection__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCollectionItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionListItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_collection_item_photo_me_collection__item_id__photo_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_card_insights_cards__card_id__insights_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardInsightsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_card_insights_cards__card_id__insights_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportCardInsightRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_export_me_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
        };
    };
    get_export_me_export__export_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_export_export_download_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_in_game_study_cards__card_id__in_game_study_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InGameStudyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_card_cards__card_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_card_price_history_cards__card_id__price_history_get: {
        parameters: {
            query?: {
                variant?: components["schemas"]["PriceVariant"];
                range?: "7" | "30" | "365" | "all";
            };
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_card_my_items_cards__card_id__my_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyCardItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
